# This image is created with Dockerfile available at
# https://git.rnd.alterway.fr/UCF/docker_yarn
image: ucf:yarn

# Install project dependencies in all cases
before_script:
    - yarn install

# Build library, create JS bundles at ./dist
build-lib:
  script:
    - yarn run build
  stage: build

# Build documentation, create files at ./dist/docs
build-docs:
  script:
    - yarn run build:docs
  stage: build

# Run all tests:
# - linter
# - unit tests
# - test coverage
test:
  script:
    - yarn test
  stage: test